name: Run tests without Docker 

on:
  workflow_dispatch: 

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4

    - name: Install python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Install requirements
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest -s -v --alluredir=allure-results

    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action
      uses: simple-elf/allure-report-action@v1.6
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Commit Allure report
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
